//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the micropython_logger package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __micropython_logger__GUIOSCILLATORFORCECONFIG_H__
#define __micropython_logger__GUIOSCILLATORFORCECONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace micropython_logger
{
  class GuiOscillatorForceConfigStatics;

  class GuiOscillatorForceConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(GuiOscillatorForceConfig &config, const GuiOscillatorForceConfig &max, const GuiOscillatorForceConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const GuiOscillatorForceConfig &config1, const GuiOscillatorForceConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, GuiOscillatorForceConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const GuiOscillatorForceConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiOscillatorForceConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiOscillatorForceConfig &config) const = 0;
      virtual void getValue(const GuiOscillatorForceConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T GuiOscillatorForceConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T GuiOscillatorForceConfig::* field;

      virtual void clamp(GuiOscillatorForceConfig &config, const GuiOscillatorForceConfig &max, const GuiOscillatorForceConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const GuiOscillatorForceConfig &config1, const GuiOscillatorForceConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, GuiOscillatorForceConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const GuiOscillatorForceConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiOscillatorForceConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiOscillatorForceConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const GuiOscillatorForceConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, GuiOscillatorForceConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, GuiOscillatorForceConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class A_ENABLE_CONTROLLER
{
  public:
    A_ENABLE_CONTROLLER()
    {
      state = true;
      name = "A_Enable_controller";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_controller"==(*_i)->name){enable_controller = boost::any_cast<bool>(val);}
        if("use_FF"==(*_i)->name){use_FF = boost::any_cast<bool>(val);}
      }
    }

    bool enable_controller;
bool use_FF;

    bool state;
    std::string name;

    
}a_enable_controller;

class B_FREQ_OSCILLATOR
{
  public:
    B_FREQ_OSCILLATOR()
    {
      state = true;
      name = "B_Freq_Oscillator";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("use_Energy_var_freq"==(*_i)->name){use_Energy_var_freq = boost::any_cast<bool>(val);}
        if("freq_value"==(*_i)->name){freq_value = boost::any_cast<double>(val);}
      }
    }

    bool use_Energy_var_freq;
double freq_value;

    bool state;
    std::string name;

    
}b_freq_oscillator;

class C_AMPLITUDE_OSCILLATOR
{
  public:
    C_AMPLITUDE_OSCILLATOR()
    {
      state = true;
      name = "C_Amplitude_Oscillator";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("min_angle"==(*_i)->name){min_angle = boost::any_cast<double>(val);}
        if("max_angle"==(*_i)->name){max_angle = boost::any_cast<double>(val);}
      }
    }

    double min_angle;
double max_angle;

    bool state;
    std::string name;

    
}c_amplitude_oscillator;

class D_LOWLEVEL_PARAMS
{
  public:
    D_LOWLEVEL_PARAMS()
    {
      state = true;
      name = "D_LowLevel_Params";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("K_stiffness"==(*_i)->name){K_stiffness = boost::any_cast<double>(val);}
        if("B_damping"==(*_i)->name){B_damping = boost::any_cast<double>(val);}
      }
    }

    double K_stiffness;
double B_damping;

    bool state;
    std::string name;

    
}d_lowlevel_params;

class E_ENERGYINTEGRATOR
{
  public:
    E_ENERGYINTEGRATOR()
    {
      state = true;
      name = "E_EnergyIntegrator";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("lb"==(*_i)->name){lb = boost::any_cast<double>(val);}
        if("ub"==(*_i)->name){ub = boost::any_cast<double>(val);}
        if("K_1"==(*_i)->name){K_1 = boost::any_cast<double>(val);}
        if("K_2"==(*_i)->name){K_2 = boost::any_cast<double>(val);}
        if("forget_factor"==(*_i)->name){forget_factor = boost::any_cast<double>(val);}
      }
    }

    double lb;
double ub;
double K_1;
double K_2;
double forget_factor;

    bool state;
    std::string name;

    
}e_energyintegrator;

class F_LOADCELL_PARAMS
{
  public:
    F_LOADCELL_PARAMS()
    {
      state = true;
      name = "F_LoadCell_Params";
    }

    void setParams(GuiOscillatorForceConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("filt_loadcell"==(*_i)->name){filt_loadcell = boost::any_cast<double>(val);}
        if("mass_foot"==(*_i)->name){mass_foot = boost::any_cast<double>(val);}
        if("l_foot"==(*_i)->name){l_foot = boost::any_cast<double>(val);}
      }
    }

    double filt_loadcell;
double mass_foot;
double l_foot;

    bool state;
    std::string name;

    
}f_loadcell_params;

}groups;



//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      bool enable_controller;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      bool use_FF;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      bool use_Energy_var_freq;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double freq_value;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double min_angle;
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double max_angle;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double K_stiffness;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double B_damping;
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double lb;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double ub;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double K_1;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double K_2;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double forget_factor;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double filt_loadcell;
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double mass_foot;
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      double l_foot;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("GuiOscillatorForceConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const GuiOscillatorForceConfig &__max__ = __getMax__();
      const GuiOscillatorForceConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const GuiOscillatorForceConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const GuiOscillatorForceConfig &__getDefault__();
    static const GuiOscillatorForceConfig &__getMax__();
    static const GuiOscillatorForceConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const GuiOscillatorForceConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void GuiOscillatorForceConfig::ParamDescription<std::string>::clamp(GuiOscillatorForceConfig &config, const GuiOscillatorForceConfig &max, const GuiOscillatorForceConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class GuiOscillatorForceConfigStatics
  {
    friend class GuiOscillatorForceConfig;

    GuiOscillatorForceConfigStatics()
    {
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT, GuiOscillatorForceConfig> Default("Default", "", 0, 0, true, &GuiOscillatorForceConfig::groups);
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorForceConfig::DEFAULT> A_Enable_controller("A_Enable_controller", "", 0, 1, true, &GuiOscillatorForceConfig::DEFAULT::a_enable_controller);
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.enable_controller = 1;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      A_Enable_controller.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiOscillatorForceConfig::enable_controller)));
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiOscillatorForceConfig::enable_controller)));
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.use_FF = 0;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.use_FF = 1;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.use_FF = 0;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      A_Enable_controller.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("use_FF", "bool", 0, "Use FF forces", "", &GuiOscillatorForceConfig::use_FF)));
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("use_FF", "bool", 0, "Use FF forces", "", &GuiOscillatorForceConfig::use_FF)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      A_Enable_controller.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorForceConfig::DEFAULT>(A_Enable_controller)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorForceConfig::DEFAULT>(A_Enable_controller)));
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT> B_Freq_Oscillator("B_Freq_Oscillator", "", 0, 2, true, &GuiOscillatorForceConfig::DEFAULT::b_freq_oscillator);
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.use_Energy_var_freq = 0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.use_Energy_var_freq = 1;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.use_Energy_var_freq = 0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      B_Freq_Oscillator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("use_Energy_var_freq", "bool", 0, "Use Energy to modulate freq", "", &GuiOscillatorForceConfig::use_Energy_var_freq)));
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<bool>("use_Energy_var_freq", "bool", 0, "Use Energy to modulate freq", "", &GuiOscillatorForceConfig::use_Energy_var_freq)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.freq_value = 0.1;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.freq_value = 0.5;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.freq_value = 0.25;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      B_Freq_Oscillator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("freq_value", "double", 0, "A double parameter representing freq adaptive oscillator", "", &GuiOscillatorForceConfig::freq_value)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("freq_value", "double", 0, "A double parameter representing freq adaptive oscillator", "", &GuiOscillatorForceConfig::freq_value)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      B_Freq_Oscillator.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT>(B_Freq_Oscillator)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT>(B_Freq_Oscillator)));
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::C_AMPLITUDE_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT> C_Amplitude_Oscillator("C_Amplitude_Oscillator", "", 0, 3, true, &GuiOscillatorForceConfig::DEFAULT::c_amplitude_oscillator);
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.min_angle = -90.0;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.min_angle = 80.0;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.min_angle = -50.0;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      C_Amplitude_Oscillator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("min_angle", "double", 0, "Lower bound of the oscillation", "", &GuiOscillatorForceConfig::min_angle)));
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("min_angle", "double", 0, "Lower bound of the oscillation", "", &GuiOscillatorForceConfig::min_angle)));
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.max_angle = 10.0;
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.max_angle = 90.0;
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.max_angle = 60.0;
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      C_Amplitude_Oscillator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("max_angle", "double", 0, "Upper bound of the oscillation", "", &GuiOscillatorForceConfig::max_angle)));
//#line 21 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("max_angle", "double", 0, "Upper bound of the oscillation", "", &GuiOscillatorForceConfig::max_angle)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      C_Amplitude_Oscillator.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::C_AMPLITUDE_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT>(C_Amplitude_Oscillator)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::C_AMPLITUDE_OSCILLATOR, GuiOscillatorForceConfig::DEFAULT>(C_Amplitude_Oscillator)));
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::D_LOWLEVEL_PARAMS, GuiOscillatorForceConfig::DEFAULT> D_LowLevel_Params("D_LowLevel_Params", "", 0, 4, true, &GuiOscillatorForceConfig::DEFAULT::d_lowlevel_params);
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.K_stiffness = 0.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.K_stiffness = 3.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.K_stiffness = 2.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      D_LowLevel_Params.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_stiffness", "double", 0, "A double parameter representing stiffness controller", "", &GuiOscillatorForceConfig::K_stiffness)));
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_stiffness", "double", 0, "A double parameter representing stiffness controller", "", &GuiOscillatorForceConfig::K_stiffness)));
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.B_damping = 0.0;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.B_damping = 0.5;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.B_damping = 0.1;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      D_LowLevel_Params.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("B_damping", "double", 0, "A double parameter representing damping controller", "", &GuiOscillatorForceConfig::B_damping)));
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("B_damping", "double", 0, "A double parameter representing damping controller", "", &GuiOscillatorForceConfig::B_damping)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      D_LowLevel_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::D_LOWLEVEL_PARAMS, GuiOscillatorForceConfig::DEFAULT>(D_LowLevel_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::D_LOWLEVEL_PARAMS, GuiOscillatorForceConfig::DEFAULT>(D_LowLevel_Params)));
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::E_ENERGYINTEGRATOR, GuiOscillatorForceConfig::DEFAULT> E_EnergyIntegrator("E_EnergyIntegrator", "", 0, 5, true, &GuiOscillatorForceConfig::DEFAULT::e_energyintegrator);
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.lb = -10.0;
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.lb = 0.0;
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.lb = -2.0;
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      E_EnergyIntegrator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("lb", "double", 0, "Hysteresis lower bound", "", &GuiOscillatorForceConfig::lb)));
//#line 29 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("lb", "double", 0, "Hysteresis lower bound", "", &GuiOscillatorForceConfig::lb)));
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.ub = 0.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.ub = 10.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.ub = 3.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      E_EnergyIntegrator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("ub", "double", 0, "Hysteresis upper bound", "", &GuiOscillatorForceConfig::ub)));
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("ub", "double", 0, "Hysteresis upper bound", "", &GuiOscillatorForceConfig::ub)));
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.K_1 = 0.01;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.K_1 = 1.0;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.K_1 = 0.3;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      E_EnergyIntegrator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_1", "double", 0, "Residual work scaling factor 1", "", &GuiOscillatorForceConfig::K_1)));
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_1", "double", 0, "Residual work scaling factor 1", "", &GuiOscillatorForceConfig::K_1)));
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.K_2 = 150.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.K_2 = 250.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.K_2 = 200.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      E_EnergyIntegrator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_2", "double", 0, "Residual work scaling factor 2", "", &GuiOscillatorForceConfig::K_2)));
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("K_2", "double", 0, "Residual work scaling factor 2", "", &GuiOscillatorForceConfig::K_2)));
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.forget_factor = 0.1;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.forget_factor = 1.0;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.forget_factor = 0.99;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      E_EnergyIntegrator.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("forget_factor", "double", 0, "Forget factor res work: closer to 1 the more it is remember from the past", "", &GuiOscillatorForceConfig::forget_factor)));
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("forget_factor", "double", 0, "Forget factor res work: closer to 1 the more it is remember from the past", "", &GuiOscillatorForceConfig::forget_factor)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      E_EnergyIntegrator.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::E_ENERGYINTEGRATOR, GuiOscillatorForceConfig::DEFAULT>(E_EnergyIntegrator)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::E_ENERGYINTEGRATOR, GuiOscillatorForceConfig::DEFAULT>(E_EnergyIntegrator)));
GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::F_LOADCELL_PARAMS, GuiOscillatorForceConfig::DEFAULT> F_LoadCell_Params("F_LoadCell_Params", "", 0, 6, true, &GuiOscillatorForceConfig::DEFAULT::f_loadcell_params);
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.filt_loadcell = 0.0;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.filt_loadcell = 1.0;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.filt_loadcell = 0.2;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      F_LoadCell_Params.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("filt_loadcell", "double", 0, "Load cell filtering closer to 0 the more filtered the signal", "", &GuiOscillatorForceConfig::filt_loadcell)));
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("filt_loadcell", "double", 0, "Load cell filtering closer to 0 the more filtered the signal", "", &GuiOscillatorForceConfig::filt_loadcell)));
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.mass_foot = 0.0;
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.mass_foot = 2.0;
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.mass_foot = 1.0;
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      F_LoadCell_Params.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("mass_foot", "double", 0, "mass of the foot attached to the loadcell", "", &GuiOscillatorForceConfig::mass_foot)));
//#line 39 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("mass_foot", "double", 0, "mass of the foot attached to the loadcell", "", &GuiOscillatorForceConfig::mass_foot)));
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __min__.l_foot = 0.0;
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __max__.l_foot = 0.5;
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __default__.l_foot = 0.15;
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      F_LoadCell_Params.abstract_parameters.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("l_foot", "double", 0, "distance from the loadcell and the weight", "", &GuiOscillatorForceConfig::l_foot)));
//#line 40 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorForce.cfg"
      __param_descriptions__.push_back(GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorForceConfig::ParamDescription<double>("l_foot", "double", 0, "distance from the loadcell and the weight", "", &GuiOscillatorForceConfig::l_foot)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      F_LoadCell_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::F_LOADCELL_PARAMS, GuiOscillatorForceConfig::DEFAULT>(F_LoadCell_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT::F_LOADCELL_PARAMS, GuiOscillatorForceConfig::DEFAULT>(F_LoadCell_Params)));
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorForceConfig::GroupDescription<GuiOscillatorForceConfig::DEFAULT, GuiOscillatorForceConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    GuiOscillatorForceConfig __max__;
    GuiOscillatorForceConfig __min__;
    GuiOscillatorForceConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const GuiOscillatorForceConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static GuiOscillatorForceConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &GuiOscillatorForceConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const GuiOscillatorForceConfig &GuiOscillatorForceConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const GuiOscillatorForceConfig &GuiOscillatorForceConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const GuiOscillatorForceConfig &GuiOscillatorForceConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<GuiOscillatorForceConfig::AbstractParamDescriptionConstPtr> &GuiOscillatorForceConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<GuiOscillatorForceConfig::AbstractGroupDescriptionConstPtr> &GuiOscillatorForceConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const GuiOscillatorForceConfigStatics *GuiOscillatorForceConfig::__get_statics__()
  {
    const static GuiOscillatorForceConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = GuiOscillatorForceConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GUIOSCILLATORFORCERECONFIGURATOR_H__
