//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the micropython_logger package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __micropython_logger__GUIOSCILLATORPOSCONFIG_H__
#define __micropython_logger__GUIOSCILLATORPOSCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace micropython_logger
{
  class GuiOscillatorPosConfigStatics;

  class GuiOscillatorPosConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(GuiOscillatorPosConfig &config, const GuiOscillatorPosConfig &max, const GuiOscillatorPosConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const GuiOscillatorPosConfig &config1, const GuiOscillatorPosConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, GuiOscillatorPosConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const GuiOscillatorPosConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiOscillatorPosConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiOscillatorPosConfig &config) const = 0;
      virtual void getValue(const GuiOscillatorPosConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T GuiOscillatorPosConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T GuiOscillatorPosConfig::* field;

      virtual void clamp(GuiOscillatorPosConfig &config, const GuiOscillatorPosConfig &max, const GuiOscillatorPosConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const GuiOscillatorPosConfig &config1, const GuiOscillatorPosConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, GuiOscillatorPosConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const GuiOscillatorPosConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiOscillatorPosConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiOscillatorPosConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const GuiOscillatorPosConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, GuiOscillatorPosConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, GuiOscillatorPosConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(GuiOscillatorPosConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class A_ENABLE_CONTROLLER
{
  public:
    A_ENABLE_CONTROLLER()
    {
      state = true;
      name = "A_Enable_controller";
    }

    void setParams(GuiOscillatorPosConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_controller"==(*_i)->name){enable_controller = boost::any_cast<bool>(val);}
        if("use_FF"==(*_i)->name){use_FF = boost::any_cast<bool>(val);}
      }
    }

    bool enable_controller;
bool use_FF;

    bool state;
    std::string name;

    
}a_enable_controller;

class B_FREQ_OSCILLATOR
{
  public:
    B_FREQ_OSCILLATOR()
    {
      state = true;
      name = "B_Freq_Oscillator";
    }

    void setParams(GuiOscillatorPosConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_AFO"==(*_i)->name){enable_AFO = boost::any_cast<bool>(val);}
        if("freq"==(*_i)->name){freq = boost::any_cast<double>(val);}
        if("offset"==(*_i)->name){offset = boost::any_cast<double>(val);}
      }
    }

    bool enable_AFO;
double freq;
double offset;

    bool state;
    std::string name;

    
}b_freq_oscillator;

class C_LOWLEVEL_PARAMS
{
  public:
    C_LOWLEVEL_PARAMS()
    {
      state = true;
      name = "C_LowLevel_Params";
    }

    void setParams(GuiOscillatorPosConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("K_stiffness"==(*_i)->name){K_stiffness = boost::any_cast<double>(val);}
        if("B_damping"==(*_i)->name){B_damping = boost::any_cast<double>(val);}
      }
    }

    double K_stiffness;
double B_damping;

    bool state;
    std::string name;

    
}c_lowlevel_params;

class D_ADAPTOSCPOS_PARAMS
{
  public:
    D_ADAPTOSCPOS_PARAMS()
    {
      state = true;
      name = "D_AdaptOscPos_Params";
    }

    void setParams(GuiOscillatorPosConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("K_freq"==(*_i)->name){K_freq = boost::any_cast<double>(val);}
        if("K_phase"==(*_i)->name){K_phase = boost::any_cast<double>(val);}
        if("K_amp"==(*_i)->name){K_amp = boost::any_cast<double>(val);}
      }
    }

    double K_freq;
double K_phase;
double K_amp;

    bool state;
    std::string name;

    
}d_adaptoscpos_params;

}groups;



//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      bool enable_controller;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      bool use_FF;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      bool enable_AFO;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double freq;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double offset;
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double K_stiffness;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double B_damping;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double K_freq;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double K_phase;
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      double K_amp;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("GuiOscillatorPosConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const GuiOscillatorPosConfig &__max__ = __getMax__();
      const GuiOscillatorPosConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const GuiOscillatorPosConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const GuiOscillatorPosConfig &__getDefault__();
    static const GuiOscillatorPosConfig &__getMax__();
    static const GuiOscillatorPosConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const GuiOscillatorPosConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void GuiOscillatorPosConfig::ParamDescription<std::string>::clamp(GuiOscillatorPosConfig &config, const GuiOscillatorPosConfig &max, const GuiOscillatorPosConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class GuiOscillatorPosConfigStatics
  {
    friend class GuiOscillatorPosConfig;

    GuiOscillatorPosConfigStatics()
    {
GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT, GuiOscillatorPosConfig> Default("Default", "", 0, 0, true, &GuiOscillatorPosConfig::groups);
GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorPosConfig::DEFAULT> A_Enable_controller("A_Enable_controller", "", 0, 1, true, &GuiOscillatorPosConfig::DEFAULT::a_enable_controller);
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.enable_controller = 1;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      A_Enable_controller.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiOscillatorPosConfig::enable_controller)));
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiOscillatorPosConfig::enable_controller)));
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.use_FF = 0;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.use_FF = 1;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.use_FF = 0;
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      A_Enable_controller.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("use_FF", "bool", 0, "Use FF forces", "", &GuiOscillatorPosConfig::use_FF)));
//#line 13 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("use_FF", "bool", 0, "Use FF forces", "", &GuiOscillatorPosConfig::use_FF)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      A_Enable_controller.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorPosConfig::DEFAULT>(A_Enable_controller)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiOscillatorPosConfig::DEFAULT>(A_Enable_controller)));
GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorPosConfig::DEFAULT> B_Freq_Oscillator("B_Freq_Oscillator", "", 0, 2, true, &GuiOscillatorPosConfig::DEFAULT::b_freq_oscillator);
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.enable_AFO = 0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.enable_AFO = 1;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.enable_AFO = 0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      B_Freq_Oscillator.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("enable_AFO", "bool", 0, "Enable Adaptive freq oscillator", "", &GuiOscillatorPosConfig::enable_AFO)));
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<bool>("enable_AFO", "bool", 0, "Enable Adaptive freq oscillator", "", &GuiOscillatorPosConfig::enable_AFO)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.freq = 0.1;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.freq = 0.5;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.freq = 0.25;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      B_Freq_Oscillator.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("freq", "double", 0, "A double parameter representing freq (not used if AFO is active)", "", &GuiOscillatorPosConfig::freq)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("freq", "double", 0, "A double parameter representing freq (not used if AFO is active)", "", &GuiOscillatorPosConfig::freq)));
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.offset = 5.0;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.offset = 80.0;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.offset = 20.0;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      B_Freq_Oscillator.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("offset", "double", 0, "A double parameter representing offset", "", &GuiOscillatorPosConfig::offset)));
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("offset", "double", 0, "A double parameter representing offset", "", &GuiOscillatorPosConfig::offset)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      B_Freq_Oscillator.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorPosConfig::DEFAULT>(B_Freq_Oscillator)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::B_FREQ_OSCILLATOR, GuiOscillatorPosConfig::DEFAULT>(B_Freq_Oscillator)));
GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::C_LOWLEVEL_PARAMS, GuiOscillatorPosConfig::DEFAULT> C_LowLevel_Params("C_LowLevel_Params", "", 0, 3, true, &GuiOscillatorPosConfig::DEFAULT::c_lowlevel_params);
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.K_stiffness = 0.0;
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.K_stiffness = 3.0;
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.K_stiffness = 1.0;
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      C_LowLevel_Params.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_stiffness", "double", 0, "A double parameter representing stiffness controller", "", &GuiOscillatorPosConfig::K_stiffness)));
//#line 22 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_stiffness", "double", 0, "A double parameter representing stiffness controller", "", &GuiOscillatorPosConfig::K_stiffness)));
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.B_damping = 0.0;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.B_damping = 0.5;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.B_damping = 0.1;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      C_LowLevel_Params.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("B_damping", "double", 0, "A double parameter representing damping controller", "", &GuiOscillatorPosConfig::B_damping)));
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("B_damping", "double", 0, "A double parameter representing damping controller", "", &GuiOscillatorPosConfig::B_damping)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      C_LowLevel_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::C_LOWLEVEL_PARAMS, GuiOscillatorPosConfig::DEFAULT>(C_LowLevel_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::C_LOWLEVEL_PARAMS, GuiOscillatorPosConfig::DEFAULT>(C_LowLevel_Params)));
GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::D_ADAPTOSCPOS_PARAMS, GuiOscillatorPosConfig::DEFAULT> D_AdaptOscPos_Params("D_AdaptOscPos_Params", "", 0, 4, true, &GuiOscillatorPosConfig::DEFAULT::d_adaptoscpos_params);
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.K_freq = 0.0;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.K_freq = 0.5;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.K_freq = 0.0;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      D_AdaptOscPos_Params.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_freq", "double", 0, "A double parameter representing gain freq adapt osc", "", &GuiOscillatorPosConfig::K_freq)));
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_freq", "double", 0, "A double parameter representing gain freq adapt osc", "", &GuiOscillatorPosConfig::K_freq)));
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.K_phase = 0.0;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.K_phase = 0.1;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.K_phase = 0.0;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      D_AdaptOscPos_Params.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_phase", "double", 0, "A double parameter representing gain phase adapt osc", "", &GuiOscillatorPosConfig::K_phase)));
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_phase", "double", 0, "A double parameter representing gain phase adapt osc", "", &GuiOscillatorPosConfig::K_phase)));
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __min__.K_amp = 0.0;
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __max__.K_amp = 0.1;
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __default__.K_amp = 0.0;
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      D_AdaptOscPos_Params.abstract_parameters.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_amp", "double", 0, "A double parameter representing gain ampl adapt osc", "", &GuiOscillatorPosConfig::K_amp)));
//#line 28 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiOscillatorPos.cfg"
      __param_descriptions__.push_back(GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr(new GuiOscillatorPosConfig::ParamDescription<double>("K_amp", "double", 0, "A double parameter representing gain ampl adapt osc", "", &GuiOscillatorPosConfig::K_amp)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      D_AdaptOscPos_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::D_ADAPTOSCPOS_PARAMS, GuiOscillatorPosConfig::DEFAULT>(D_AdaptOscPos_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT::D_ADAPTOSCPOS_PARAMS, GuiOscillatorPosConfig::DEFAULT>(D_AdaptOscPos_Params)));
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr(new GuiOscillatorPosConfig::GroupDescription<GuiOscillatorPosConfig::DEFAULT, GuiOscillatorPosConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    GuiOscillatorPosConfig __max__;
    GuiOscillatorPosConfig __min__;
    GuiOscillatorPosConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const GuiOscillatorPosConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static GuiOscillatorPosConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &GuiOscillatorPosConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const GuiOscillatorPosConfig &GuiOscillatorPosConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const GuiOscillatorPosConfig &GuiOscillatorPosConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const GuiOscillatorPosConfig &GuiOscillatorPosConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<GuiOscillatorPosConfig::AbstractParamDescriptionConstPtr> &GuiOscillatorPosConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<GuiOscillatorPosConfig::AbstractGroupDescriptionConstPtr> &GuiOscillatorPosConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const GuiOscillatorPosConfigStatics *GuiOscillatorPosConfig::__get_statics__()
  {
    const static GuiOscillatorPosConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = GuiOscillatorPosConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GUIOSCILLATORPOSRECONFIGURATOR_H__
