//#line 2 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the micropython_logger package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __micropython_logger__GUISMWALKINGCONFIG_H__
#define __micropython_logger__GUISMWALKINGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace micropython_logger
{
  class GuiSMWalkingConfigStatics;

  class GuiSMWalkingConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      virtual ~AbstractParamDescription() = default;

      virtual void clamp(GuiSMWalkingConfig &config, const GuiSMWalkingConfig &max, const GuiSMWalkingConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const GuiSMWalkingConfig &config1, const GuiSMWalkingConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, GuiSMWalkingConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const GuiSMWalkingConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiSMWalkingConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiSMWalkingConfig &config) const = 0;
      virtual void getValue(const GuiSMWalkingConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T GuiSMWalkingConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T GuiSMWalkingConfig::* field;

      virtual void clamp(GuiSMWalkingConfig &config, const GuiSMWalkingConfig &max, const GuiSMWalkingConfig &min) const override
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const GuiSMWalkingConfig &config1, const GuiSMWalkingConfig &config2) const override
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, GuiSMWalkingConfig &config) const override
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const GuiSMWalkingConfig &config) const override
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, GuiSMWalkingConfig &config) const override
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const GuiSMWalkingConfig &config) const override
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const GuiSMWalkingConfig &config, boost::any &val) const override
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      virtual ~AbstractGroupDescription() = default;

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, GuiSMWalkingConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, GuiSMWalkingConfig &top) const override
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const override
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T PT::* field;
      std::vector<GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);


      }
    }

    

    bool state;
    std::string name;

    class A_ENABLE_CONTROLLER
{
  public:
    A_ENABLE_CONTROLLER()
    {
      state = true;
      name = "A_Enable_controller";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("enable_controller"==(*_i)->name){enable_controller = boost::any_cast<bool>(val);}
      }
    }

    bool enable_controller;

    bool state;
    std::string name;

    
}a_enable_controller;

class B_STANCE_STATE_PARAMS
{
  public:
    B_STANCE_STATE_PARAMS()
    {
      state = true;
      name = "B_Stance_State_Params";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("stance_q_eq"==(*_i)->name){stance_q_eq = boost::any_cast<double>(val);}
        if("stance_q_dot_eq"==(*_i)->name){stance_q_dot_eq = boost::any_cast<double>(val);}
        if("stance_dt"==(*_i)->name){stance_dt = boost::any_cast<double>(val);}
        if("stance_K"==(*_i)->name){stance_K = boost::any_cast<double>(val);}
        if("stance_B"==(*_i)->name){stance_B = boost::any_cast<double>(val);}
      }
    }

    double stance_q_eq;
double stance_q_dot_eq;
double stance_dt;
double stance_K;
double stance_B;

    bool state;
    std::string name;

    
}b_stance_state_params;

class C_EARLY_SWING_PARAMS
{
  public:
    C_EARLY_SWING_PARAMS()
    {
      state = true;
      name = "C_Early_Swing_Params";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("earlySwing_q_eq"==(*_i)->name){earlySwing_q_eq = boost::any_cast<double>(val);}
        if("earlySwing_q_dot_eq"==(*_i)->name){earlySwing_q_dot_eq = boost::any_cast<double>(val);}
        if("earlySwing_dt"==(*_i)->name){earlySwing_dt = boost::any_cast<double>(val);}
        if("earlySwing_K"==(*_i)->name){earlySwing_K = boost::any_cast<double>(val);}
        if("earlySwing_B"==(*_i)->name){earlySwing_B = boost::any_cast<double>(val);}
      }
    }

    double earlySwing_q_eq;
double earlySwing_q_dot_eq;
double earlySwing_dt;
double earlySwing_K;
double earlySwing_B;

    bool state;
    std::string name;

    
}c_early_swing_params;

class D_LATE_SWING_PARAMS
{
  public:
    D_LATE_SWING_PARAMS()
    {
      state = true;
      name = "D_Late_Swing_Params";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("lateSwing_q_eq"==(*_i)->name){lateSwing_q_eq = boost::any_cast<double>(val);}
        if("lateSwing_q_dot_eq"==(*_i)->name){lateSwing_q_dot_eq = boost::any_cast<double>(val);}
        if("lateSwing_dt"==(*_i)->name){lateSwing_dt = boost::any_cast<double>(val);}
        if("lateSwing_K"==(*_i)->name){lateSwing_K = boost::any_cast<double>(val);}
        if("lateSwing_B"==(*_i)->name){lateSwing_B = boost::any_cast<double>(val);}
      }
    }

    double lateSwing_q_eq;
double lateSwing_q_dot_eq;
double lateSwing_dt;
double lateSwing_K;
double lateSwing_B;

    bool state;
    std::string name;

    
}d_late_swing_params;

class E_TRESH_PARAMS
{
  public:
    E_TRESH_PARAMS()
    {
      state = true;
      name = "E_Tresh_Params";
    }

    void setParams(GuiSMWalkingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("vel_tresh"==(*_i)->name){vel_tresh = boost::any_cast<double>(val);}
        if("Fz_tresh"==(*_i)->name){Fz_tresh = boost::any_cast<double>(val);}
      }
    }

    double vel_tresh;
double Fz_tresh;

    bool state;
    std::string name;

    
}e_tresh_params;

}groups;



//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      bool enable_controller;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double stance_q_eq;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double stance_q_dot_eq;
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double stance_dt;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double stance_K;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double stance_B;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double earlySwing_q_eq;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double earlySwing_q_dot_eq;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double earlySwing_dt;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double earlySwing_K;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double earlySwing_B;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double lateSwing_q_eq;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double lateSwing_q_dot_eq;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double lateSwing_dt;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double lateSwing_K;
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double lateSwing_B;
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double vel_tresh;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      double Fz_tresh;
//#line 231 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("GuiSMWalkingConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const GuiSMWalkingConfig &__max__ = __getMax__();
      const GuiSMWalkingConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const GuiSMWalkingConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const GuiSMWalkingConfig &__getDefault__();
    static const GuiSMWalkingConfig &__getMax__();
    static const GuiSMWalkingConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const GuiSMWalkingConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void GuiSMWalkingConfig::ParamDescription<std::string>::clamp(GuiSMWalkingConfig &config, const GuiSMWalkingConfig &max, const GuiSMWalkingConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class GuiSMWalkingConfigStatics
  {
    friend class GuiSMWalkingConfig;

    GuiSMWalkingConfigStatics()
    {
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT, GuiSMWalkingConfig> Default("Default", "", 0, 0, true, &GuiSMWalkingConfig::groups);
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiSMWalkingConfig::DEFAULT> A_Enable_controller("A_Enable_controller", "", 0, 1, true, &GuiSMWalkingConfig::DEFAULT::a_enable_controller);
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.enable_controller = 1;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.enable_controller = 0;
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      A_Enable_controller.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiSMWalkingConfig::enable_controller)));
//#line 12 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<bool>("enable_controller", "bool", 0, "Enable controller", "", &GuiSMWalkingConfig::enable_controller)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      A_Enable_controller.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiSMWalkingConfig::DEFAULT>(A_Enable_controller)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::A_ENABLE_CONTROLLER, GuiSMWalkingConfig::DEFAULT>(A_Enable_controller)));
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::B_STANCE_STATE_PARAMS, GuiSMWalkingConfig::DEFAULT> B_Stance_State_Params("B_Stance_State_Params", "", 0, 2, true, &GuiSMWalkingConfig::DEFAULT::b_stance_state_params);
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.stance_q_eq = 0.0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.stance_q_eq = 90.0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.stance_q_eq = 0.0;
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      B_Stance_State_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::stance_q_eq)));
//#line 16 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::stance_q_eq)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.stance_q_dot_eq = 0.0;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.stance_q_dot_eq = 2.0;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.stance_q_dot_eq = 0.0;
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      B_Stance_State_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::stance_q_dot_eq)));
//#line 17 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::stance_q_dot_eq)));
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.stance_dt = 0.0;
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.stance_dt = 1.0;
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.stance_dt = 1.0;
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      B_Stance_State_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::stance_dt)));
//#line 18 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::stance_dt)));
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.stance_K = 0.0;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.stance_K = 3.0;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.stance_K = 0.1;
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      B_Stance_State_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_K", "double", 0, "Stance Stiffness ", "", &GuiSMWalkingConfig::stance_K)));
//#line 19 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_K", "double", 0, "Stance Stiffness ", "", &GuiSMWalkingConfig::stance_K)));
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.stance_B = 0.0;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.stance_B = 0.3;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.stance_B = 0.01;
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      B_Stance_State_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_B", "double", 0, "time to go", "", &GuiSMWalkingConfig::stance_B)));
//#line 20 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("stance_B", "double", 0, "time to go", "", &GuiSMWalkingConfig::stance_B)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      B_Stance_State_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::B_STANCE_STATE_PARAMS, GuiSMWalkingConfig::DEFAULT>(B_Stance_State_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::B_STANCE_STATE_PARAMS, GuiSMWalkingConfig::DEFAULT>(B_Stance_State_Params)));
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::C_EARLY_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT> C_Early_Swing_Params("C_Early_Swing_Params", "", 0, 3, true, &GuiSMWalkingConfig::DEFAULT::c_early_swing_params);
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.earlySwing_q_eq = 0.0;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.earlySwing_q_eq = 90.0;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.earlySwing_q_eq = 50.0;
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      C_Early_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::earlySwing_q_eq)));
//#line 23 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::earlySwing_q_eq)));
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.earlySwing_q_dot_eq = 0.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.earlySwing_q_dot_eq = 2.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.earlySwing_q_dot_eq = 0.0;
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      C_Early_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::earlySwing_q_dot_eq)));
//#line 24 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::earlySwing_q_dot_eq)));
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.earlySwing_dt = 0.0;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.earlySwing_dt = 2.0;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.earlySwing_dt = 2.0;
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      C_Early_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::earlySwing_dt)));
//#line 25 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::earlySwing_dt)));
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.earlySwing_K = 0.0;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.earlySwing_K = 3.0;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.earlySwing_K = 0.1;
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      C_Early_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_K", "double", 0, "Early swing Stiffness", "", &GuiSMWalkingConfig::earlySwing_K)));
//#line 26 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_K", "double", 0, "Early swing Stiffness", "", &GuiSMWalkingConfig::earlySwing_K)));
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.earlySwing_B = 0.0;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.earlySwing_B = 0.3;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.earlySwing_B = 0.01;
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      C_Early_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_B", "double", 0, "Early Swing Damping", "", &GuiSMWalkingConfig::earlySwing_B)));
//#line 27 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("earlySwing_B", "double", 0, "Early Swing Damping", "", &GuiSMWalkingConfig::earlySwing_B)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      C_Early_Swing_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::C_EARLY_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT>(C_Early_Swing_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::C_EARLY_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT>(C_Early_Swing_Params)));
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::D_LATE_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT> D_Late_Swing_Params("D_Late_Swing_Params", "", 0, 4, true, &GuiSMWalkingConfig::DEFAULT::d_late_swing_params);
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.lateSwing_q_eq = 0.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.lateSwing_q_eq = 90.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.lateSwing_q_eq = 0.0;
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      D_Late_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::lateSwing_q_eq)));
//#line 30 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_q_eq", "double", 0, "equilibrium angle", "", &GuiSMWalkingConfig::lateSwing_q_eq)));
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.lateSwing_q_dot_eq = 0.0;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.lateSwing_q_dot_eq = 2.0;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.lateSwing_q_dot_eq = 0.0;
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      D_Late_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::lateSwing_q_dot_eq)));
//#line 31 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_q_dot_eq", "double", 0, "equilibrium velocity", "", &GuiSMWalkingConfig::lateSwing_q_dot_eq)));
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.lateSwing_dt = 0.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.lateSwing_dt = 2.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.lateSwing_dt = 2.0;
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      D_Late_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::lateSwing_dt)));
//#line 32 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_dt", "double", 0, "time to go", "", &GuiSMWalkingConfig::lateSwing_dt)));
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.lateSwing_K = 0.0;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.lateSwing_K = 3.0;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.lateSwing_K = 0.1;
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      D_Late_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_K", "double", 0, "Late Swing Stiffnes", "", &GuiSMWalkingConfig::lateSwing_K)));
//#line 33 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_K", "double", 0, "Late Swing Stiffnes", "", &GuiSMWalkingConfig::lateSwing_K)));
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.lateSwing_B = 0.0;
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.lateSwing_B = 0.3;
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.lateSwing_B = 0.01;
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      D_Late_Swing_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_B", "double", 0, "Late Swing Damping", "", &GuiSMWalkingConfig::lateSwing_B)));
//#line 34 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("lateSwing_B", "double", 0, "Late Swing Damping", "", &GuiSMWalkingConfig::lateSwing_B)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      D_Late_Swing_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::D_LATE_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT>(D_Late_Swing_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::D_LATE_SWING_PARAMS, GuiSMWalkingConfig::DEFAULT>(D_Late_Swing_Params)));
GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::E_TRESH_PARAMS, GuiSMWalkingConfig::DEFAULT> E_Tresh_Params("E_Tresh_Params", "", 0, 5, true, &GuiSMWalkingConfig::DEFAULT::e_tresh_params);
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.vel_tresh = 5.0;
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.vel_tresh = 30.0;
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.vel_tresh = 10.0;
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      E_Tresh_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("vel_tresh", "double", 0, "vel tresh", "", &GuiSMWalkingConfig::vel_tresh)));
//#line 37 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("vel_tresh", "double", 0, "vel tresh", "", &GuiSMWalkingConfig::vel_tresh)));
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __min__.Fz_tresh = 5.0;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __max__.Fz_tresh = 50.0;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __default__.Fz_tresh = 10.0;
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      E_Tresh_Params.abstract_parameters.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("Fz_tresh", "double", 0, "Fz tresh", "", &GuiSMWalkingConfig::Fz_tresh)));
//#line 38 "/home/research23/exo_CBM/catkin_ws/src/micropython_logger/cfg/GuiSMWalking.cfg"
      __param_descriptions__.push_back(GuiSMWalkingConfig::AbstractParamDescriptionConstPtr(new GuiSMWalkingConfig::ParamDescription<double>("Fz_tresh", "double", 0, "Fz tresh", "", &GuiSMWalkingConfig::Fz_tresh)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      E_Tresh_Params.convertParams();
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.groups.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::E_TRESH_PARAMS, GuiSMWalkingConfig::DEFAULT>(E_Tresh_Params)));
//#line 122 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT::E_TRESH_PARAMS, GuiSMWalkingConfig::DEFAULT>(E_Tresh_Params)));
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      Default.convertParams();
//#line 245 "/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py"
      __group_descriptions__.push_back(GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr(new GuiSMWalkingConfig::GroupDescription<GuiSMWalkingConfig::DEFAULT, GuiSMWalkingConfig>(Default)));
//#line 369 "/opt/ros/noetic/share/dynamic_reconfigure/templates/ConfigType.h.template"

      for (std::vector<GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<GuiSMWalkingConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    GuiSMWalkingConfig __max__;
    GuiSMWalkingConfig __min__;
    GuiSMWalkingConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const GuiSMWalkingConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static GuiSMWalkingConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &GuiSMWalkingConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const GuiSMWalkingConfig &GuiSMWalkingConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const GuiSMWalkingConfig &GuiSMWalkingConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const GuiSMWalkingConfig &GuiSMWalkingConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<GuiSMWalkingConfig::AbstractParamDescriptionConstPtr> &GuiSMWalkingConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<GuiSMWalkingConfig::AbstractGroupDescriptionConstPtr> &GuiSMWalkingConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const GuiSMWalkingConfigStatics *GuiSMWalkingConfig::__get_statics__()
  {
    const static GuiSMWalkingConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = GuiSMWalkingConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __GUISMWALKINGRECONFIGURATOR_H__
