## *********************************************************
##
## File autogenerated for the micropython_logger package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [{'name': 'int_param', 'type': 'int', 'default': 50, 'level': 0, 'description': 'An integer parameter', 'min': 0, 'max': 100, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'double_param', 'type': 'double', 'default': 1.0, 'level': 0, 'description': 'A double parameter', 'min': 0.0, 'max': 10.0, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}, {'name': 'str_param', 'type': 'str', 'default': 'Hello', 'level': 0, 'description': 'A string parameter', 'min': '', 'max': '', 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'std::string', 'cconsttype': 'const char * const'}, {'name': 'bool_param', 'type': 'bool', 'default': True, 'level': 0, 'description': 'A boolean parameter', 'min': False, 'max': True, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'bool', 'cconsttype': 'const bool'}], 'groups': [], 'srcline': 244, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

